blogpost/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    TicketlistView, TikectDetailView, TicketCreateView, TicketUpdateView,
    TicketDeleteView, ReviewlistView, ReviewDetailView, ReviewCreateView,
    ReviewUpdateView, ReviewDeleteView, TicketReviewCreateAIOView
    )


urlpatterns = [
    path("tickets/", TicketlistView.as_view(), name="ticket-list"),
    path("tickets/create/", TicketCreateView.as_view(), name="ticket-create"),
    path("tickets/create-aio/", TicketReviewCreateAIOView.as_view(), name="ticket-create-aio"),
    path("tickets/<slug:slug>/", TikectDetailView.as_view(), name="ticket-detail"),
    path("tickets/<slug:slug>/update/", TicketUpdateView.as_view(), name="ticket-update"),
    path("tickets/<slug:slug>/delete/", TicketDeleteView.as_view(), name="ticket-delete"),
    path("tickets/<slug:ticket_slug>/reviews/", ReviewlistView.as_view(), name="ticket-review-list"),
    path("tickets/<slug:ticket_slug>/reviews/create/", ReviewCreateView.as_view(), name="ticket-review-create"),
    path("tickets/<slug:ticket_slug>/reviews/<slug:slug>/", ReviewDetailView.as_view(), name="ticket-review-detail"),
    path("tickets/<slug:ticket_slug>/reviews/<slug:slug>/update/", ReviewUpdateView.as_view(),
         name="ticket-review-update"),
    path("tickets/<slug:ticket_slug>/reviews/<slug:slug>/delete/", ReviewDeleteView.as_view(),
         name="ticket-review-delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) if settings.DEBUG else None

feed/urls.py
from django.urls import path

from .views import TheFeedPageView, MyFeedPageView


urlpatterns = [
    path("", TheFeedPageView.as_view(), name="feed"),
    path("my-feed/", MyFeedPageView.as_view(), name="my-feed"),
               ]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("auth/", include(("authentification.urls", "auth"))),
    path("flux/", include(("blogpost.urls", "flux"))),
    path("feed/", include(("feed.urls", "feed"))),
    path("follow/", include(("followup.urls", "follow"))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) if settings.DEBUG else None

blogpost/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from autoslug import AutoSlugField
from django.utils.text import slugify


class Ticket(models.Model):
    """
    This class represents the Ticket model.

    Attributes:
    title: CharField
    slug: AutoSlugField
    description: TextField
    user: ForeignKey
    image: ImageField
    time_created: DateTimeField

    Methods:
        __str__(): Returns a string representation of the ticket,
        displaying its title.
    """
    title = models.CharField(max_length=128, verbose_name="Nom du livre ou de l'article")
    slug = AutoSlugField(unique=True, populate_from="title", max_length=256)
    description = models.TextField(
        max_length=2048, blank=True, verbose_name="Description du livre ou de l'article")
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="tickets",
        verbose_name="Utilisateur",
        null=True
        )
    time_created = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Date de la demande de la critique sur un livre/article"
        )
    image = models.ImageField(
        null=True, blank=True,
        upload_to='ticket_images/',
        verbose_name="Image du livre/article",
        default="ticket_images/django.png",
        )

    content_type = "TICKET"

    class Meta:
        verbose_name = "Livre ou Article"
        ordering = ["-time_created"]

    def __str__(self):
        """Return the title of the Tiket."""
        slugify(self.title)
        return self.title

    def get_absolute_url(self):
        """Return the absolute url of the ticket"""
        return reverse("flux:ticket-detail", kwargs={"slug": self.slug})


class Review(models.Model):
    """
    Represents a review associated with a ticket, including rating, user...

    Attributes:
        ticket: ForeignKey
        rating: PositiveSmallIntegerField (0 to 5).
        user: ForeignKey
        headline: CharField
        slug: AutoSlugField
        body: TextField
        time_created: DateTimeField

    Methods:
        __str__(): Returns a string representation of the review, indicating the associated ticket and user.
    """
    RATING_CHOICES = [
        (0, '☆☆☆☆☆'),
        (1, '★☆☆☆☆'),
        (2, '★★☆☆☆'),
        (3, '★★★☆☆'),
        (4, '★★★★☆'),
        (5, '★★★★★'),
    ]

    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE, related_name="reviews")
    # validates rating must be between 0 and 5
    rating = models.PositiveSmallIntegerField(
        choices=RATING_CHOICES,
        validators=[MinValueValidator(0), MaxValueValidator(5)],
        verbose_name="Note sur 5 étoiles",
    )
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="reviews")
    headline = models.CharField(max_length=128, verbose_name="En-tête de la critique")
    slug = AutoSlugField(populate_from="headline", unique=True, max_length=256)
    body = models.TextField(max_length=8192, blank=True, verbose_name="Commentaires ")
    time_created = models.DateTimeField(auto_now_add=True, verbose_name="Date de publication de la critique")

    content_type = "REVIEW"

    class Meta:
        verbose_name = "Critique"
        ordering = ["-time_created"]

    def __str__(self):
        """Return a string representation of the review."""
        return f'Critique "{self.headline}" pour "{self.ticket.title}"'

    def get_absolute_url(self):
        """Return the absolute url of the review"""
        return reverse("flux:ticket-review-detail", kwargs={"ticket_slug": self.ticket.slug, "slug": self.slug})

blogpost/forms.py
from django import forms

from .models import Ticket, Review


class TicketForm(forms.ModelForm):
    """
    ModelForm for creating or update a new Ticket.
    """
    class Meta:
        model = Ticket
        fields = ["title", "description", "image", ]
        help_texts = {
            "title": "Entrez le nom ici",
            "description": "Entrez la description ici",
        }


class ReviewForm(forms.ModelForm):
    """
    ModelForm for creating or update a new Review.
    """
    class Meta:
        model = Review
        fields = ["headline", "body", "rating", ]
        widgets = {
            "rating": forms.RadioSelect(choices=Review.RATING_CHOICES)
        }
        help_texts = {
            "headline": "Entrez la critique ici",
            "body": "Entrez le commentaire ici",
            "rating": "choisissez la note en nombre d'étoiles",
        }


class TicketCreateForm(forms.ModelForm):
    """Form for creating a new Ticket and review all in one."""
    class Meta:
        model = Ticket
        fields = ('title', 'description', 'image')


class ReviewCreateForm(forms.ModelForm):
    """Form for creating a new Review and Ticket all in one."""
    class Meta:
        model = Review
        fields = ('headline', 'rating', 'body')

blogpost/views.py
from django.shortcuts import redirect, render
from django.views.generic import (ListView, DetailView, CreateView,
                                  UpdateView, DeleteView, TemplateView
                                  )
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import TicketForm, ReviewForm, TicketCreateForm, ReviewCreateForm
from .models import Ticket, Review

"""
Definition of views classes for the flux.
"""


class TicketlistView(LoginRequiredMixin, ListView):
    """View for the ticket list page."""
    model = Ticket
    template_name = "blogpost/ticket_list.html"
    context_object_name = "tickets"


class TikectDetailView(LoginRequiredMixin, DetailView):
    """View for the ticket detail page."""
    model = Ticket
    template_name = "blogpost/ticket_detail.html"
    context_object_name = "ticket"


class TicketCreateView(LoginRequiredMixin, CreateView):
    """View for the creation of a ticket."""
    model = Ticket
    template_name = "blogpost/ticket_create.html"
    form_class = TicketForm

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form."""
        # print(self.object)   # self.object est une instance du modèle Ticket
        # print(type(self.object))  # self.object est une instance de <class 'blogpost.models.Ticket'>
        return reverse("flux:ticket-detail", kwargs={"slug": self.object.slug})

    def form_valid(self, form):
        """
        Avant que le formulaire ne soit validé et que l'instance de modèle ne
        soit sauvegardée, l'attribut user de l'instance est défini sur
        l'utilisateur actuellement connecté (self.request.user). Cela permet
        de lier l'instance de modèle à l'utilisateur qui a soumis le formulaire.
        """
        form.instance.user = self.request.user  # form.instance est une instance du modèle Ticket
        # form.save().user = self.request.user    # form.save() est également une instance du modèle Ticket
        # print(type(form.instance)) # form.instance est une instance de <class 'blogpost.models.Ticket'>
        # print(form.instance)
        return super().form_valid(form)


class TicketUpdateView(LoginRequiredMixin, UpdateView):
    """View for the update of a ticket."""
    model = Ticket
    template_name = "blogpost/ticket_update.html"
    form_class = TicketForm

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form."""
        return reverse("flux:ticket-detail", kwargs={"slug": self.object.slug})

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class TicketDeleteView(LoginRequiredMixin, DeleteView):
    """View for the deletion of a ticket."""
    model = Ticket
    template_name = "blogpost/ticket_delete.html"

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form."""
        return reverse("flux:ticket-list")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class ReviewlistView(LoginRequiredMixin, ListView):
    """View for the review list page."""
    template_name = "blogpost/review_list.html"
    context_object_name = "reviews"

    def get_context_data(self, **kwargs):
        """Return the context data to use for forms on this view."""
        context = super().get_context_data(**kwargs)
        context.update({"ticket": Ticket.objects.get(slug=self.kwargs["ticket_slug"])})
        return context

    def get_queryset(self):
        """Return the list of items for this view."""
        return Review.objects.filter(ticket__slug=self.kwargs["ticket_slug"])


class ReviewDetailView(LoginRequiredMixin, DetailView):
    """View for the review detail page."""
    model = Review
    template_name = "blogpost/review_detail.html"
    context_object_name = "review"
    # slug_url_kwarg = "review_slug"
    # pk_url_kwarg = "review_id"


class ReviewCreateView(LoginRequiredMixin, CreateView):
    """View for the creation of a review."""
    model = Review
    template_name = "blogpost/review_create.html"
    form_class = ReviewForm

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form."""
        return reverse("flux:ticket-review-detail",
                       kwargs={"ticket_slug": self.object.ticket.slug, "slug": self.object.slug})

    def get_context_data(self, **kwargs):
        """Return the context data to use for forms on this view."""
        context = super().get_context_data(**kwargs)
        context.update({"ticket": Ticket.objects.get(slug=self.kwargs["ticket_slug"])})
        return context

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        form.instance.user = self.request.user
        form.instance.ticket = Ticket.objects.get(slug=self.kwargs["ticket_slug"])
        # print(type(form.instance)) # form.instance est une instance du modèle Review
        return super().form_valid(form)


class ReviewUpdateView(LoginRequiredMixin, UpdateView):
    """View for the update of a review."""
    model = Review
    template_name = "blogpost/review_update.html"
    form_class = ReviewForm

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form."""
        return reverse("flux:ticket-review-detail",
                       kwargs={"ticket_slug": self.object.ticket.slug, "slug": self.object.slug})

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class ReviewDeleteView(LoginRequiredMixin, DeleteView):
    """View for the deletion of a review."""
    model = Review
    template_name = "blogpost/review_delete.html"

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form."""
        return reverse("flux:ticket-review-list", kwargs={"ticket_slug": self.object.ticket.slug})

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


# Avec la classe CreateView
class TicketReviewCreateAIOView(LoginRequiredMixin, CreateView):
    """View for the creation of a review and ticket all in one."""
    model = Ticket
    template_name = "blogpost/ticket_review_create_aio.html"
    form_class = TicketForm

    def get_context_data(self, **kwargs):
        """Return the context data to use for forms on this view."""
        context = super().get_context_data(**kwargs)
        context.update({"form_review": ReviewForm()})
        return context

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        form.instance.user = self.request.user
        ticket = form.save()
        form_review = ReviewForm(self.request.POST)
        form_review.instance.user = self.request.user
        form_review.instance.ticket = ticket
        form_review.save()
        return redirect(reverse("flux:ticket-list"))


# Avec la classe TemplateView
class TicketReviewCreateAIOView1(LoginRequiredMixin, TemplateView):
    """View for the creation of a review and ticket all in one."""
    template_name = "blogpost/ticket_review_create_aio.html"

    def get_context_data(self, **kwargs):
        """Return the context data to use for forms on this view."""
        context = super().get_context_data(**kwargs)
        context.update({"form_ticket": TicketForm(), "form_review": ReviewForm()})
        return context

    def post(self, request, *args, **kwargs):
        """Handle POST requests: create a ticket and a review."""
        form_ticket = TicketCreateForm(request.POST, request.FILES)
        form_review = ReviewCreateForm(request.POST)
        if not form_ticket.is_valid() and not form_review.is_valid():
            context = {"form_ticket": form_ticket,
                       "form_review": form_review
                       }
            return self.render_to_response(context)
        # si tout va bien, créer le ticket et la review)
        form_ticket.instance.user = self.request.user
        ticket = form_ticket.save()
        form_review.instance.user = self.request.user
        form_review.instance.ticket = ticket
        form_review.save()
        return redirect(reverse("flux:ticket-list"))


# Avec les Vues basées sur les fonctions
def ticket_review_all_in_one_view(request):
    """    View for the creation of review by zero page.
    """
    if request.method == "POST":
        form = TicketForm(request.POST, request.FILES)
        form_1 = ReviewForm(request.POST)
        if form.is_valid() and form_1.is_valid():
            form.save()
            form_1.save()
        return redirect(request.path)
    else:

        form = TicketForm()
        form_1 = ReviewForm()
    return render(request, "blogpost/review_by_0.html", {"form": form, "form_1": form_1})

blogpost/templates/blogpost/review_create.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="form-title">Créer une critique sur:&nbsp;<span style="color: rgb(61, 61, 61);">{{ ticket.title }}</span></h3>
    <br>
    <a href="{% url 'flux:ticket-review-list' ticket_slug=ticket.slug %}" class="return-link">Retour aux critiques du Livre/Article</a>
    <br><br>

    <form method="POST" class="form-body">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button-1">Ajouter une nouvelle critique</button>
    </form>
{% endblock %}

blogpost/templates/blogpost/review_delete.html
{% extends "base.html" %}

{% block title %}<title>Supprimer la critique</title>{% endblock %}

{% block content %}
    <a href="{% url 'flux:ticket-review-detail' ticket_slug=review.ticket.slug slug=review.slug %}" class="return-link">Retour aux critiques</a>
    <h3>Suppression de la critique: &nbsp;<span style="color: rgb(61, 61, 61);">{{ review.headline }}</span></h3>
    <form method="POST" class="form-body">
        {% csrf_token %}
        <p>Voulez-vous vraiment supprimer la critique "{{ review.headline }}"?</p>

        <button type="submit" class="button-1">Supprimer</button>
    </form>

{% endblock %}

blogpost/templates/blogpost/review_detail.html
{% extends "base.html" %}

{% block title %}<title>{{ review.headline }}</title>{% endblock %}

{% block content %}
    <nav>
        <ul class="nav-list-vertical">
            <li><a href="{% url 'flux:ticket-review-list' ticket_slug=review.ticket.slug %}" class="reviw-detail-nav-element">Retour aux critiques du livre/article</a></li>
            {% if review.user == request.user %}
            <li><a href="{% url 'flux:ticket-review-update' ticket_slug=review.ticket.slug slug=review.slug %}" class="reviw-detail-nav-element">Modifier la critique</a></li>
            <li> <a href="{% url 'flux:ticket-review-delete' ticket_slug=review.ticket.slug slug=review.slug %}" class="reviw-detail-nav-element">Supprimer la critique</a></li>
            {% endif %}
        </ul>
    </nav>
    <hr class="hr-1">

    <h4>La critique sur <span style="color: grey;">{{ review.ticket }}</span> : <br> <span style="color: rgb(38, 36, 140);">{{ review.headline }}</span></h4>
    <p class="rating">{{ review.get_rating_display }}</p>
    <p style="margin: 50px 0;">{{ review.body }}</p>

{% endblock %}

blogpost/templates/blogpost/review_list.html
{% extends "base.html" %}

{% block title %}<title>Les Critiques</title>{% endblock %}

{% block content %}
    <h3>Les Critiques sur : &nbsp;<span style="color: rgb(61, 61, 61);">{{ ticket.title }}<span></h3>
    <hr class="hr-1">

    <a href="{% url 'flux:ticket-review-create' ticket_slug=ticket.slug %}" class="return-link">Ajouter une critique</a>

    <ul class="grid-container">
        {% for review in reviews %}
            <li class="review-list-element">
                <a href="{% url 'flux:ticket-review-detail' ticket_slug=review.ticket.slug slug=review.slug %}" class="detail-link">
                    <h4>
                        {{ review.headline }} ({{ forloop.counter }})
                        <a href="{% url 'flux:ticket-review-update' ticket_slug=review.ticket.slug slug=review.slug %}" class="edit-link">
                            Modifier &nbsp;
                        </a>
                        <a href="{% url 'flux:ticket-review-delete' ticket_slug=review.ticket.slug slug=review.slug %}" class="delete-link">
                            Supprimer
                        </a>
                    </h4>
                </a>
                <p class="rating">{{ review.get_rating_display }}</p>
                <p>{{ review.body|truncatewords:30 }}</p>
            </li>

        {% endfor %}
    </ul>

{% endblock %}

blogpost/templates/blogpost/review_update.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'flux:ticket-review-detail' ticket_slug=review.ticket.slug slug=review.slug %}" class="return-link">Retour à la critique sans modification</a>
    <h3 class="form-title">Modifier la Critique :&nbsp;<span style="color: rgb(61, 61, 61);">{{review.headline}}</span></h3>
    <form method="POST" class="form-body">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button-1">Modifier la critique</button>
    </form>

{% endblock %}

blogpost/templates/blogpost/ticket_create.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="form-title">Création d'un ticket</h3>

    <a href="{% url 'feed:feed' %}" class="return-link">Retour au flux</a>

    <form method="POST" class="form-body" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Créer un nouveau ticket" class="button-1">
    </form>
{% endblock %}

blogpost/templates/blogpost/ticket_delete.html
{% extends "base.html" %}

{% block title %}<title>Supprimer un ticket</title>{% endblock %}

{% block content %}
    <a href="{% url 'feed:feed' %}" class="return-link">Retour au flux</a>

    <form method="POST" class="form-body">
        <p>Voulez-vous supprimer le ticket "{{ ticket.title }}"?</p>

        {% csrf_token %}

        <button type="submit" class="button-1">Supprimer</button>
    </form>

{% endblock %}

blogpost/templates/blogpost/ticket_detail.html
{% extends "base.html" %}

{% block title %}<title>{{ ticket.title }}</title>{% endblock %}

{% block content %}
    <main class="ticket-detail">
        <nav>
            <div class="nav-list-vertical">
                <li><a href="{% url 'feed:feed' %}" class="ticket-detail-nav-element">Retour au flux</a></li>
                <li><a href="{% url 'flux:ticket-review-create' ticket_slug=ticket.slug %}" class="ticket-detail-nav-element">Ajouter un commentaire sur ce livre ou cet article</a></li>

                {% if ticket.user == request.user %}
                    <li><a href="{% url 'flux:ticket-update' slug=ticket.slug %}" class="ticket-detail-nav-element">Modifier le ticket</a></li>
                {% endif %}
                {% if ticket.user == request.user %}
                    <li><a href="{% url 'flux:ticket-delete' slug=ticket.slug %}" class="ticket-detail-nav-element">Supprimer le ticket</a></li>
                {% endif %}

                <li><a href="{% url 'flux:ticket-review-list' ticket_slug=ticket.slug %}" class="ticket-detail-nav-element">Afficher en détail les critiques sur ce livre/article</a></li>
            </div>
        </nav>
        <hr class="hr-1">
        <h3>{{ ticket.title }}</h3>
        <img src="{{ ticket.image.url }}" alt="L'image de '{{ ticket.title }}'" width='150px'>
        <p>Post de: {{ ticket.user }}</p>
        <p>Date de la demande: {{ ticket.time_created }}</p>
        <p>Description: {{ ticket.description }}</p>
        <br><br>
        <h3>Synthèse des critiques dédiées à : &nbsp;<span style="color: rgb(61, 61, 61);">{{ ticket.title }}</span></h3>
        <div class="grid-container">
    {% for review in ticket.reviews.all %}
            <div>
                <h4>{{ forloop.counter }} - {{ review.headline }}</h4>
                <p>{{ review.body }}</p>
            </div>
        {% endfor %}
        </div>
        <br><br>
    </main>

{% endblock %}

blogpost/templates/blogpost/ticket_list.html
{% extends "base.html" %}

{% block title %}<title>Les Livres ou articles</title>{% endblock %}

{% block content %}
    <h1>Les Billets</h1>
    <hr>
        <button>
            <h3><a href="{% url 'flux:ticket-create' %}" style="color: rgb(255, 0, 255);">Demander une critique pour un livre ou un article</a></h3>
        </button>

        <button>
            <h3><a href="{% url 'flux:ticket-create-aio' %}" style="color: rgb(255, 0, 255);">Commenter un livre ou un article</a></h3>
        </button>
    <ul>
    {% for ticket in tickets %}
    <li>
        <a href="{% url 'flux:ticket-detail' slug=ticket.slug %}">
            <h3>
                {{ ticket.title }} - ({{ forloop.counter }}) -
                <a href="{% url 'flux:ticket-update' slug=ticket.slug %}">
                    [Modifier]
                </a>
                <a href="{% url 'flux:ticket-delete' slug=ticket.slug %}">
                    [Supprimer]
                </a>
            </h3>
        <img src="{{ ticket.image.url }}" alt="L'image de '{{ ticket.title }}'" width="75px">
        </a>
        <p>{{ ticket.description|truncatewords:30 }}</p>

    </li>
    {% endfor %}
    </ul>
{% endblock %}

blogpost/templates/blogpost/ticket_review_create_aio.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="form-title">Créer un ticket et ajouter une critique</h3>

    <a href="{% url 'feed:feed' %}" class="return-link">Retour au Flux</a>

    <form method="POST" enctype="multipart/form-data" class="form-body">
        <p class="ticket-review-create-para">Veuillez créer le ticket:</p>
        {% csrf_token %}
        {{ form.as_p }}
        <p class="ticket-review-create-para">Veuillez saisir la critique associée: </p>
        {{ form_review.as_p }}
        <input type="submit" value="Créer" class="button-1">
    </form>
{% endblock %}

blogpost/templates/blogpost/ticket_update.html
{% extends "base.html" %}

{% block content %}
    <h3 class="form-title">Modifier un ticket</h3>
    <a href="{% url 'feed:feed' %}" class="return-link">Retour au flux</a>
    <br><br>

    <form method="POST" class="form-body" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Modifier le ticket" class="button-1">
    </form>

{% endblock %}